on:
  push:
    branches:
      - develop
name: Develop
jobs:

  snapshot:
    # needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: 'sed -i -e ''s/"version": "\(.*\)"/"version": "\1-snapshot.''`git rev-list --count HEAD`''"/'' package.json'
    - run: npm install
    - run: npm run build
    - run: npm publish --tag snapshot
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
